# Generated by Django 5.2.6 on 2025-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Cliente'), ('seller', 'Vendedor')], default='customer', max_length=20),
        ),
    ]
